[workspace]
resolver = "2"
members = ["packages/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ro80t/fast-static-server"
readme = "README.md"

[workspace.dependencies]
tokio = "1"
axum = "0.8"
tower = "0.5"
tower-http = "0.7"
percent-encoding = "2"
clap = { version = "4", features = ["derive"] }
fast-static-server = { path = "packages/fast-static-server", version = "0.1.0" }

[profile.release]
lto = true
codegen-units = 1
